baseURL = "ekboehm.github.io"
title = "Eduard Boehm"
theme = "etch-custom"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
aboutExcerptSentences = 3
dark = "off"

[params]
  description = "Welcome to my website! I am a fifth year Ph.D. student in Economics at Princeton University. I work in the intersection of Industrial Organization and Public Economics."
  copyright = "Copyright © 2023 Eduard Boehm"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/about_me"
    weight = 10

  [[menu.main]]
    identifier = "research"
    name = "Research"
    title = "Research"
    url = "/research/research"
    weight = 20

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    title = "Teaching"
    url = "/teaching/teaching"
    weight = 30

    [[menu.main]]
    identifier = "cv"
    name = "CV"
    title = "cv"
    url = "https://www.dropbox.com/scl/fi/o2ltxddwvqthol2am4or1/boehm_cv.pdf?rlkey=x9cqf6tpy97xrvmmkwl6oony9&dl=0"
    weight = 40

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
