baseURL = "ekboehm.github.io"
title = "Eduard Boehm"
theme = "etch-custom"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
aboutExcerptSentences = 3


[params]
  description = "Welcome to my website! I am a fifth year Ph.D. student in Economics at Princeton University. I work in the intersection of Industrial Organization and Public Economics."
  copyright = "Copyright © 2023 Eduard Boehm"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "research"
    name = "research"
    title = "Research"
    url = "/research/research"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about/about_me"
    weight = 20

  [[menu.main]]
    identifier = "teaching"
    name = "teaching"
    title = "Teaching"
    url = "/teaching/teaching"
    weight = 30

    [[menu.main]]
    identifier = "cv"
    name = "cv"
    title = "cv"
    url = "https://www.dropbox.com/s/1xw5sc2cs49307o/boehm_cv.pdf?dl=0"
    weight = 40

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
